//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProtoPad_Client.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ProtoPad_Client.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///	&lt;meta http-equiv=&apos;X-UA-Compatible&apos; content=&apos;IE=edge;chrome=1&apos;&gt;
        ///	&lt;style&gt;
        ///	*{font-family: Arial; font-size:11px}
        ///	table{ border-collapse: collapse;margin:5px;border: 2px solid #69f;}
        ///	td,th{text-align:left;border:1px solid grey; padding: 2px;vertical-align: top}
        ///	th{background-color:#cde;}
        ///	thead td{background-color:#69f;color:white;font-weight:bold}
        ///	.leftarrow{
        ///		width: 0; 
        ///		height: 0; 
        ///		border-top: 6px solid transparent;
        ///		border-bottom: 6px solid transparent; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ResultHtmlWrap {
            get {
                return ResourceManager.GetString("ResultHtmlWrap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Enter any code you wish to run on the Android device or emulator app
        ///// You can use the &apos;window&apos; variable, which is the main application window
        ///// You can also use &apos;activity&apos;, which is the main application activity
        ///
        ///// New to ProtoPad? Uncomment and try the sample code below!
        ///
        ////*
        ///var url = new URL(&quot;http://www.spc-intheworld.com/wp-content/uploads/2013/03/MtN-Nepal.jpg&quot;);
        ///var connection = url.OpenConnection() as HttpURLConnection;
        ///connection.DoInput = true;
        ///Bitmap bitmap = null;
        ///var downloadBit [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleCodeAndroidProgram {
            get {
                return ResourceManager.GetString("SampleCodeAndroidProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Enter any code you wish to run on the iOS simulator app
        ///// You can use the &apos;window&apos; variable, which is the main application window
        ///// You can also use &apos;appDelegate&apos;, which is the main application delegate
        ///
        ///// New to ProtoPad? Uncomment and try the sample code below!
        ///
        ////*
        ///var nsUrl = new NSUrl(&quot;http://www.spc-intheworld.com/wp-content/uploads/2013/03/MtN-Nepal.jpg&quot;);
        ///var data = NSData.FromUrl(nsUrl);
        ///var image = new UIImage(data);
        ///var imageFilePath = Path.Combine(Environment.GetFolderPath(Environ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SampleCodeiOSProgram {
            get {
                return ResourceManager.GetString("SampleCodeiOSProgram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // Running locally - use the Connect button to start working with your mobile app!
        ///
        ///// Or run any code you want to test locally using regular .Net (4.5), such as:
        ///// Regex.Match(&quot;Inspect Regular Expression matches&quot;, &quot;ess?&quot;).Dump();.
        /// </summary>
        internal static string SampleCodeRegularProgram {
            get {
                return ResourceManager.GetString("SampleCodeRegularProgram", resourceCulture);
            }
        }
    }
}
